"""add company financial profiles

Revision ID: 5c9dabbfe3e3
Revises: b0c556800f3c
Create Date: 2026-08-27 23:43:18.977950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9dabbfe3e3'
down_revision: Union[str, Sequence[str], None] = 'b0c556800f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financial_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('monthly_revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('monthly_expenses', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('monthly_payroll', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('monthly_marketing', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('monthly_software', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('accounts_payable', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('monthly_debt_payment', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('fiscal_year_start', sa.String(length=10), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_financial_profiles_company_id'), 'company_financial_profiles', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_financial_profiles_company_id'), table_name='company_financial_profiles')
    op.drop_table('company_financial_profiles')
    # ### end Alembic commands ###
